---
tags: [messaging, rabbitmq]
projects: [spring-amqp]
---
:spring_boot_version: 1.3.3.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-messaging-rabbitmq
This guide walks you through the process of setting up a RabbitMQ AMQP server that  publishes and subscribes to messages.

== What you'll build

You'll build an application that publishes a message using Spring AMQP's `RabbitTemplate` and subscribes to the message on a link:/understanding/POJO[POJO] using `MessageListenerAdapter`.

== Set up RabbitMQ broker
Before you can build your messaging application, you need to set up the server that will handle receiving and sending messages.

RabbitMQ is an AMQP server. The server is freely available at http://www.rabbitmq.com/download.html. You can download it manually, or if you are using a Mac with homebrew:

----
brew install rabbitmq
----

Unpack the server and launch it with default settings.

----
rabbitmq-server
----

You should see something like this:

....
            RabbitMQ 3.1.3. Copyright (C) 2007-2013 VMware, Inc.
##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
##  ##
##########  Logs: /usr/local/var/log/rabbitmq/rabbit@localhost.log
######  ##        /usr/local/var/log/rabbitmq/rabbit@localhost-sasl.log
##########
            Starting broker... completed with 6 plugins.
....

Next play with sender and receiver to play with messages
